name: Python Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/python-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest
